; We use these 3 ROM routines
ROM_KEYBOARD        equ $02bb
ROM_DECODE          equ $07bd
ROM_COPY_REGISTERS  equ $0724

; Enum used by STR_DETERMINE_SQUARE_CONTENTS
SQUARE_IS_DIFFERENT_COLOUR equ 0
SQUARE_IS_EMPTY equ 1
SQUARE_IS_BOARD_EDGE equ 2
SQUARE_IS_SAME_COLOUR equ 3

